### ISSUE TITLE
File uri in build envelope method

### ISSUE THREAD

**Issue by insha786** [docusign/mobile-android-sdk#13]
hi
i am trying to give uri as
file = new File(Environment.getExternalStorageDirectory().getAbsolutePath(), "/ResumeAndroid.pdf");
f= new File("file://"+file) ;
.uri(f.toString())
.name("ResumeAndroid.pdf")
its giving me error as
: Unknown exception in loading document: File is not a valid, parseable, password-free PDF
tried also
.uri("file:///storage/emulated/0/ResumeAndroid.pdf")
.name("ResumeAndroid.pdf")
but same error
can you suggest any solution?

in phone path when clicking on file details to get path its showing---> storage/emulated/0/documents/ResumeAndroid.pdf"

also in logcat i am getting 2020-12-28 19:15:52.108 20175-20175/com.example.docusignapp W/PDFTronToolsInitializer: Tried to auto-initialize PDFTron SDK but no license key was found. Please add your license as described in this article: https://www.pdftron.com/documentation/android/guides/getting-started/add-license.
Kindly help

**Comment by naveentds** [comment]
Hi @insha786,
Can you try the following:
 
File file = new File(Environment.getExternalStorageDirectory().getAbsolutePath(), "/ResumeAndroid.pdf");
URI fileURI = file.toURI();
Then,

.uri(fileURI.toString());

Let us know how it goes.

**Comment by insha786** [comment]
It's working fine now.

Can you please let me help how to skip logging in Android sdk.I have
integrated sdk with my app but I want to skip login.
How to use jwt for this and which api is needed to get called.

Thanks for your help!

Insha

**Comment by naveentds** [comment]
@insha786  
You can refer to the answer at https://github.com/docusign/mobile-android-sdk/issues/14 for achieving that.

**Comment by inshaaziz** [comment]
Thank you for your response!

Helped alot

**Comment by insha786** [comment]
Hi Team,

I am trying to integrate latest release of android sdk with my Android app
however I am facing dependency conflicts due to androidx version. Please
let me know is there any sdk version which do not have androidx dependency.

Thanks & Regards
Insha

**Comment by naveentds** [comment]
@insha786 DocuSign Android SDK has a requisite for androidX dependency and we don't support non-androidX. 
We suggest you to migrate your app to androidX https://developer.android.com/jetpack/androidx/migrate.

**Comment by insha786** [comment]
Thank you for your response.

Currently our app is not supporting androidx may be aftter  sometime we
will migrate our application.

Thankyou so much!

**Comment by inshaaziz** [comment]
Hi Naveed

I am trying to call Docusignapp(different app having one activity) from a
test app(other app). I am facing one issue after finishing signing in on
success method of online signing I have called finish method also but
control never goes to onaActivitResult of calling activity. It goes into
loop calling docusign then onActivifystart.

Kindly help!

**Comment by naveentds** [comment]
Hi @inshaaziz 
It's not an issue in SDK. 
Can you check in your DocuSignApp, once you receive success callback for online signing, you need to invoke setResult(OK, data) and then invoke finish(). 
Then, you will get control over onActivityResult() of the calling activity of your TestApp. In onActivityResult() of your TestApp, make sure you don't invoke again startActivity of your DocuSignApp.

**Comment by insha786** [comment]
Thank you, it worked..
