### ISSUE TITLE
How can we skip the login or authenticate implicitly using the SDK methods or some other way?

### ISSUE THREAD

**Issue by inshaaziz** [docusign/mobile-android-sdk#14]
I have integrated the docuSign Android SDK in my app and been able to achieve embedded signing. But it asks for the customer to login before signing the document. As its a customer facing app, we dont want them to enter the organisation docusign credentials. 
How can we skip the login or authenticate implicitly using the SDK methods or some other way?

 

Thanks in Advance!!

**Comment by naveentds** [comment]
Hi @inshaaziz 
In Android SDK, we provide the following apis to login or authenticate.
1.  Login with Access Token:
   You can invoke the following SDK API:
   ```
// accessToken - Access Token which authenticates the user
// refreshToken - If the access token can be refreshed, the refresh token. Optional
// expiresIn - The number of seconds from the time the access token was provisioned to when it will expire
try {
    DSAuthenticationDelegate docusignAuthDelegate = DocuSign.getInstance().getAuthenticationDelegate();
    docusignAuthDelegate.login(accessToken, refreshToken, expiresIn, context,
        new DSAuthenticationListener() {
            @Override
            public void onSuccess(@NonNull DSUser user) {
                // TODO: handle successful authentication here
            }
 
            @Override
            public void onError(@NonNull DSAuthenticationException exception) {
                // TODO: handle authentication failure here
            }
        }
    );
} catch (DocuSignNotInitializedException exception) {
    // TODO: handle error. This means the SDK object was not properly initialized
}
```
   You can retrieve access token the following ways:
 - Using JWT Grant authentication by following steps mentioned at https://developers.docusign.com/platform/auth/jwt/jwt-get-token/
  - Using Authorization Code Grant by following the steps mentioned at https://developers.docusign.com/platform/auth/authcode/authcode-get-token/
  
Using JWT Grant authentication to fetch access token needs to be implemented at your backend and once your server receives access token from DocuSign using this approach, then your server needs to pass that access token and the expiration time to your app and your app can invoke the above mentioned Android SDK login api with access token and expiration time.
  

2. Login using OAuth:
    UI is displayed where user enters credentials.
   Get the OAuth Client Id/Integration key, secret key and redirectUri from your account. (Please refer to   https://developers.docusign.com/platform/auth/authcode/authcode-get-token/ on how to retrieve the clientId, secretKey and   redirectUri from your account).

   While initializing the DocuSign SDk, pass these values as shown in below
  ```
   DocuSign.init(
   context,
   clientId,
   secretKey,
   redirectUri,
   DSMode.DEBUG
  ).setEnvironment(environment)

  DSAuthenticationDelegate authenticationDelegate = DocuSign.getInstance().getAuthenticationDelegate();
  authenticationDelegate.login(REQUEST_LOGIN, this, new DSAuthenticationListener() {
  }
  ```
  This will open the OAuth login screen. Enter your username and password and you should be able to login.

In your use case, you can use SDK 'Login with Access Token' approach.

**Comment by inshaaziz** [comment]
Thanks a lot, I will try and revert incase any other help is required.

**Comment by nelson-glauber** [comment]
I'm having this exact same problem... 
I've tried the three types of authentication but all of them is requiring the user email when the browser is opened... 
- I have a integration key (marked as "Implicit Grant")
- This integration has "Redirect URIs" defined as "company://response"
- I'm just opening the following URL on the browser: 
https://account-d.docusign.com/oauth/auth?response_type=token&scope=signature&client_id=MY_CLIENT_ID&redirect_uri=company://response

@inshaaziz / @naveentds could you help me on this?

**Comment by naveentds** [comment]
Hi @nelson-glauber 
You can integrate DocuSign Android SDK into your Android app and then try invoking the above mentioned DocuSign Android SDK login api.

**Comment by nelson-glauber** [comment]
thanks @naveentds. I am doing this and still is requesting the user's email...
I'm initializing the SDK...
```
DocuSign.init(
    this,
    myIntegrationKey, // Currently is a "Authorization Code Grant" 
    secret, // I create one in the portal
    redirect, // I also defined an URI
    DSMode.DEBUG
)
DocuSign.getInstance().setEnvironment(DSEnvironment.DEMO_ENVIRONMENT)
```
and then, I'm incalling:
```
val docusignAuthDelegate = DocuSign.getInstance().getAuthenticationDelegate()
docusignAuthDelegate.login(REQUEST_DOCUSIGN_LOGIN, requireContext(),
    object : DSAuthenticationListener {
        override fun onSuccess(user: DSUser) {
            Log.d("NGVL", "${user.accountId} | ${user.email} | ${user.name} | ${user.userId}")
        }
        override fun onError(exception: DSAuthenticationException) {
            Log.e("NGVL", "Erro1", exception)
            exception.printStackTrace()
        }
    }
)
```
This is what I get...
<img src="https://user-images.githubusercontent.com/20464075/113748120-7e409580-96de-11eb-8b8a-c9de82be7643.png" width=300/>

**Comment by naveentds** [comment]
@nelson-glauber  You are using OAuth login using DocuSign Android SDK and you need DocuSign user credentials to login. You need to create a DocuSign account in the web portal and use those credentials to login here. For adding integration key, take a look at https://support.docusign.com/guides/ndse-admin-guide-api-and-keys.

**Comment by nelson-glauber** [comment]
Ok... Let me see if I can make myself clear:
I don't want that the users of my app have to create a DocuSign account. I thought that I should simply use a "Implicit Grant" token like described here:
https://developers.docusign.com/platform/auth/implicit/implicit-get-token/
I tried, and didn't work for me. So I tried the SDK and it also requests DocuSign account.

Could you explain how to get an access token without asks the users of my app to create a DocuSign account.
Sorry if it sounds a dummy question but the steps described in the documentation didn't work for me.

Thanks in advance @naveentds

**Comment by inshaaziz** [comment]
Hi
In Android SDK, we provide the following apis to login or authenticate.

   1. Login with Access Token:
   You can invoke the following SDK API:

// accessToken - Access Token which authenticates the user
// refreshToken - If the access token can be refreshed, the refresh
token. Optional
// expiresIn - The number of seconds from the time the access token
was provisioned to when it will expire
try {
 DSAuthenticationDelegate docusignAuthDelegate =
DocuSign.getInstance().getAuthenticationDelegate();
 docusignAuthDelegate.login(accessToken, refreshToken, expiresIn, context,
     new DSAuthenticationListener() {
         @Override
         public void onSuccess(@NonNull DSUser user) {
             // TODO: handle successful authentication here
         }

         @Override
         public void onError(@NonNull DSAuthenticationException exception) {
             // TODO: handle authentication failure here
         }
     }
 );
} catch (DocuSignNotInitializedException exception) {
 // TODO: handle error. This means the SDK object was not properly initialized
}

You can retrieve access token the following ways:

   - Using JWT Grant authentication by following steps mentioned at
   https://developers.docusign.com/platform/auth/jwt/jwt-get-token/
   - Using Authorization Code Grant by following the steps mentioned at
   https://developers.docusign.com/platform/auth/authcode/authcode-get-token/

Using JWT Grant authentication to fetch access token needs to be
implemented at your backend and once your server receives access token from
DocuSign using this approach, then your server needs to pass that access
token and the expiration time to your app and your app can invoke the above
mentioned Android SDK login api with access token and expiration time.

   1.

   Login using OAuth:
   UI is displayed where user enters credentials.
   Get the OAuth Client Id/Integration key, secret key and redirectUri from
   your account. (Please refer to
   https://developers.docusign.com/platform/auth/authcode/authcode-get-token/
on
   how to retrieve the clientId, secretKey and redirectUri from your account).

   While initializing the DocuSign SDk, pass these values as shown in below

 DocuSign.init(
 context,
 clientId,
 secretKey,
 redirectUri,
 DSMode.DEBUG
).setEnvironment(environment)

DSAuthenticationDelegate authenticationDelegate =
DocuSign.getInstance().getAuthenticationDelegate();
authenticationDelegate.login(REQUEST_LOGIN, this, new
DSAuthenticationListener() {
}

This will open the OAuth login screen. Enter your username and password and
you should be able to login.

**Comment by naveentds** [comment]
Thanks @inshaaziz for providing the info.

@nelson-glauber 
You cannot use 'Implicit grant' approach to login for your use-case. As per the  https://developers.docusign.com/platform/auth/implicit/implicit-get-token/, UI will be shown to user to enter DocuSign account credentials. 
In DocuSign Android SDK, you can use login with JWT Grant authentication approach if you don't want users to enter DocuSign account credentials in the UI. For details checkout  https://developers.docusign.com/platform/auth/jwt/jwt-get-token/

Using JWT Grant authentication to fetch access token needs to be
implemented at your backend and once your server receives access token from
DocuSign using this approach, then your server needs to pass that access
token and the expiration time to your app and your app can invoke the above
mentioned Android SDK login api with access token and expiration time. ( 1. Login with Access Token)
