### ISSUE TITLE
API difference with iOS sdk

### ISSUE THREAD

**Issue by myamolane** [docusign/mobile-android-sdk#15]
Hello. Is it able for this sdk to support the same login methods as iOS sdk ?
![image](https://user-images.githubusercontent.com/26702359/116218606-4678bb00-a77d-11eb-9ff2-0b3ef959e061.png)

**Comment by InbarGazit** [comment]
@myamolane  This method you are using with the iOS SDK is the older way and is less secure. We strongly encourage you to change to OAuth 2.0. The Android SDK only support OAuth 2.0 as it is much more secure. In the future we may decide to require everyone to use OAuth 2.0 to improve security.

**Comment by naveentds** [comment]
@myamolane Currently, Android SDK supports the following login api:
- Login with OAuth
- Login with Access token
