### ISSUE TITLE
[Question] Is it possible to open a signed document?

### ISSUE THREAD

**Issue by nglauber** [docusign/mobile-android-sdk#16]
I'd like to "review" the signature after the user sign the document offline. Is it possible?

Here the steps that I want to achieve:

Sign process
1.  I create an envelope using DSEnvelope.Builder
2. Then I call composeAndSendEnvelope to save the envelope into the local DB
3. Finally the signOffline is called and the user signs the document

Everything is fine til this point. Now, it's what I want to achieve:
4. I'm calling getCachedEnvelope to get the envelope created on step #2
5. Then I'm calling composeAndSendEnvelope passing the envelope get on step #4

Expected result: 
the offline sign ceremony is started again, but with the document already signed.
Actual result: 
A exception is thrown -> DSSigningException: Envelope has no active recipients

One thing that I tried was change the recipient status to SENT, but with this change, the user have to sign again...

**Comment by naveentds** [comment]
@nglauber
If you have not yet synced the signed document to DocuSign using sync() api, you can just recreate the envelope and signOffline again. 
If you have synced the signed document to DocuSign and would like to review the signed document, you can use SDK's downloadCompletedEnvelopeDocument() api to preview the signed document. 
Currently, SDK does not support reviewing the signature after the document is signed.
