### ISSUE TITLE
How to add anchorString using SDK while creating the envelope?

### ISSUE THREAD

**Issue by sharadhihosamani** [docusign/mobile-android-sdk#17]
Hi ,

1) I am using EnvelopeDelegate's composeAndSendEnvelope method provided by SDK to create an envelope using a local PDF document. I need to place the SIGNATURE tab based on an **anchor string**. Is there a way to achieve this using any of the SDK features?

2) How do we add **htmlDefinition** while creating document using DSDocument.Builder()?

3) How do we skip the Post signing success screen (PFA) and directly get callback to CreateEnvelopeAndLaunchOnlineSigning's onSuccess method?

Thanks!
<img width="365" alt="Screenshot 2021-05-25 at 11 12 28 AM" src="https://user-images.githubusercontent.com/22168878/119445853-13f5ba00-bd4b-11eb-8f2f-41a44836c00e.png">

**Comment by naveentds** [comment]
Hi @sharadhihosamani,
This is on our roadmap and is being prioritized, not currently supported in SDK.

**Comment by sharadhihosamani** [comment]
Thanks for the confirmation and update.
