### ISSUE TITLE
How to restrict pre-populating  of signatures during signing session?

### ISSUE THREAD

**Issue by sharadhihosamani** [docusign/mobile-android-sdk#20]
Hi,

I don't want the user to see any of the existing signatures during a signing session in the app. Is there a way to restrict this from the code or through account settings on the portal?

Basically need to avoid users from seeing below screen:

<img width="388" alt="Screenshot 2021-07-14 at 10 50 03 AM" src="https://user-images.githubusercontent.com/22168878/125567916-cdaa6083-4d20-4adf-ad47-efc0fde7b2c5.png">

**Comment by naveentds** [comment]
Hi @sharadhihosamani 
In the DocuSign web portal, 
 - Navigate to Settings->Signing Settings-> Signature Adoption Configuration 
 - Select 'Disable Style selection'
This will not display preloaded user's signature.

**Comment by sharadhihosamani** [comment]
@naveentds This option is disabled for my account on the portal. 
<img width="996" alt="Screenshot 2021-07-19 at 10 15 08 AM" src="https://user-images.githubusercontent.com/22168878/126158782-ae7b75ba-185a-42b8-b695-609cea1f6691.png">

**Comment by naveentds** [comment]
@sharadhihosamani 
I'd recommend reaching out to DocuSign Support and asking them to enable "Disable Style Signature" for you.
It is a backend setting that is not enabled by default.

**Comment by sharadhihosamani** [comment]
Thanks @naveentds
