### ISSUE TITLE
How can get signed date in android ?

### ISSUE THREAD

**Issue by voilet0604** [docusign/mobile-android-sdk#22]
![signedDate](https://user-images.githubusercontent.com/10805525/128962792-4bf1e5ab-77ac-4e40-9508-a55958fc562e.png)

**Comment by naveentds** [comment]
Hi @voilet0604 
We will provide the access to signedDate attribute in our next SDK release.

Thanks

**Comment by voilet0604** [comment]
@naveentds Thanks

**Comment by naveentds** [comment]
@voilet0604, We released SDK 1.4.0. You should be able to access signedDate now with this release.
