### ISSUE TITLE
Support for PowerForms

### ISSUE THREAD

**Issue by imroopesh-ai** [docusign/mobile-android-sdk#23]
We are trying to integrate Docusign PowerForms into our healthcare service. We have a use case where all our patients need to eSign couple of forms before the treatment.

It would be great to have the Mobile SDK support PowerForms to easily sign the envelopes.

**Comment by naveentds** [comment]
Hi @imroopesh-ai  This is an enhancement and we need to add support in SDK.
We will check if this can be added to our Product Roadmap.

**Comment by naveentds** [comment]
Hi @imroopesh-ai:

```Powerforms``` feature request has been added to the roadmap. Closing it for now as ```captive signing``` based integration is more favorable at this point.

Thanks for bringing it up.
