### ISSUE TITLE
"User Account does not allow offline usage" when minifyEnabled is true

### ISSUE THREAD

**Issue by nglauber** [docusign/mobile-android-sdk#24]
I'm using DocuSign SDK version 1.4.0 and everything is working fine when I generate an APK with `minifyEnabled` set to false. However, when I set the `minifyEnabled` to true, I get this error when I'm trying to cache a template:
```
 2021-11-03 21:21:16.116 22101-22101/com.myapp.mobile E/b$b: cacheTemplate::onError
    com.docusign.androidsdk.exceptions.DSTemplateException: User Account does not allow offline usage.
        at com.docusign.androidsdk.delegates.DSTemplateDelegate.cacheTemplate(:304)
```
I already added the rules in `proguard-rules.pro` as specified in the [documentation](https://github.com/docusign/mobile-android-sdk#online-signing).

I also checked [this](https://support.docusign.com/en/articles/DocuSign-Developer-FAQs-Android-SDK#minifyEnabled) and [this](https://support.docusign.com/en/articles/DocuSign-Developer-FAQs-Android-SDK#Offline-Usage-Error) . 

Any thoughts?

**Comment by naveentds** [comment]
Hi @nglauber 
Can you try adding the following to your proguard rules in the App:
```
-keepclassmembers class com.docusign.esign.** { *; }
-keep class com.docusign.esign.** { *; }
```

**Comment by nglauber** [comment]
Thanks @naveentds. It worked! 
Is this something that I've missed or is it a lack in the documentation?

**Comment by naveentds** [comment]
Glad it worked for you @nglauber 
We have updated proguard rules as part of SDK 1.4.0 release and I recently updated those proguard rules in the README documentation in the github repo.
