### ISSUE TITLE
Create Envelope from Template

### ISSUE THREAD

**Issue by ominibyte** [docusign/mobile-android-sdk#28]
Is it possible to create an Envelope from a Template? I cannot find any method to do that currently. Maybe I am missing something so let me explain my workflow:

I have a template from which I want to create envelopes for multiple clients. The signers would be using my application to sign the envelope directly in the App without having to log in to DocuSign (So I assume they would fall under the In-Person Signer category). For this, I am using the login method with access token.

Currently, after the login,
i. I get the template using `templateDelegate.getTemplate`
ii. I then cache the template using `templateDelegate.cacheTemplate`
iii. Next, I call `templateDelegate.useTemplateOffline` to start the offline-signing process.

My main concern is that `templateDelegate.useTemplateOffline` uses `DSEnvelopeDefaults` which contains `DSRecipientDefault` that doesn't have the option for `hostEmail` and `hostName` as opposed to `DSEnvelopeRecipient` that has the `hostEmail` and `hostName` fields when creating an envelope.

If I try using the `DSUser` information obtained from the login with access token step as the recipient  (which I assume is wrong), the `DSUser` details show as the recipient on the Use Template page instead of the In-Person Signer details which I supplied as seen below:

<img width="262" alt="Screenshot 2022-03-03 at 5 01 48 AM" src="https://user-images.githubusercontent.com/7020327/156542282-4e20c55c-9c31-4129-aa36-6c4429653846.png">

So, please correct me if I am wrong but I am thinking the solution for me seems to be creating an envelope from the template and supplying the `DSEnvelopeRecipient` with the `hostEmail` and `hostName` fields. Or, if there is a way to skip the Use Template page altogether so that it doesn't show up. 

I am not sure how to proceed and would really need help in figuring out the correct way to get this done.

**Comment by naveentds** [comment]
You can skip 'UseTemplate' screen by providing DSEnvelopeDefaults values in the following API:
``` 
templateDelegate.useTemplate(,..,envelopeDefaults,...)  
```` 
Please refer to the documentation for providing envelope defaults at https://docusign.github.io/mobile-android-sdk/sdk-common/com.docusign.androidsdk.dsmodels/-d-s-recipient-default/index.html

Here is the code snippet for providing values in EnvelopeDefaults:

```
val recipientDefaults = mutableListOf<DSRecipientDefault>()
// For IPS,
recipientDefault = DSRecipientDefault(recipientEmail: <hostEmail>, recipientName: <hostName>, inPersonSignerName: <InPersonSigner Name>, ....)
recipientDefaults.add(recipientDefault)
envelopeDefaults.recipientDefaults = recipientDefaults
```
Note that 
```
val user = authDelegate.getLoggedInUser()
<hostEmail> = user.email
<hostName> = user.name
```

**Comment by ominibyte** [comment]
@naveentds, thank you for your response. I have done exactly this but I am still greeted with the Use Template screen.
I am using `useTemplateOffline` and I cannot find a `useTemplate` method. 

You can also see from the screenshot I posted earlier that the button says "`Sign`" which I believe means that all the required fields have been provided. I'm not sure if I am missing something.

Also, if it will be helpful, these are the versions I am using:
```
implementation 'com.docusign:androidsdk:1.5.3'
implementation 'com.docusign:sdk-common:1.5.3'
implementation 'com.docusign:sdk-offline-signing:1.5.3'
```
