### ISSUE TITLE
Set read only field does not work

### ISSUE THREAD

**Issue by aperdomom** [docusign/mobile-android-sdk#3]
I'm trying to set a field as read only on my template but it does not work.

here is a screen shot of Docusign web when I set the "read only" option:
<img width="407" alt="Screen Shot 2020-08-24 at 13 42 49" src="https://user-images.githubusercontent.com/9371485/91088884-02428300-e610-11ea-8c9d-f8f4816d3a4b.png">

 Here is how I set the tabValueDefaults:
`private fun getTemplateTabData() =
        mapOf<String, Any>(
                "Name $tabKeyName" to user.firstName +" "+ user.lastName,
                "Text $tabKeyTest" to "test read only new value",
                "Text $tabKeyTitle0" to user.title
            )`

Here is a screen shot of the template on my Android device to show how I still can edit the field:
<img width="354" alt="Screen Shot 2020-08-24 at 13 55 03" src="https://user-images.githubusercontent.com/9371485/91089883-6fa2e380-e611-11ea-8188-2159eddb3dbb.png">

**Comment by skongara** [comment]
Hi @aperdomom,
We fixed this issue in our new DocuSign Android SDK version 1..0.3. Please try with the latest release.

**Comment by aperdomom** [comment]
I tried it and it is fixed. thanks
