### ISSUE TITLE
docusign issue

### ISSUE THREAD

**Issue by inshaaziz** [docusign/mobile-android-sdk#30]
i was using  'com.docusign:androidsdk:1.1.4' but it is not working now 
now updated to 1.5.3 but imports are not working can you suggest on this?

**Comment by naveentds** [comment]
Hi @inshaaziz 
Can you take a look at the README file in https://github.com/docusign/mobile-android-sdk and check if you set maven url and SDK dependencies correctly.
You might want to update few imports as some of the class names might have been changed as part of SDK componentization.
You can also take a look at SDK sample app at https://github.com/docusign/mobile-android-sdk/tree/master/docusign-sdk-sample-kotlin for reference.
