### ISSUE TITLE
Appearance Delegate didn't work correctly

### ISSUE THREAD

**Issue by yusufonderd** [docusign/mobile-android-sdk#33]
Hi,
I try to customize docusign with my own brand name. But it doesn't work these lines. Only status bar color changed. The other configuration for instance brand logo, toolbar button color, button text color doesn't change.

```
val appearanceDelegate = DocuSign.getInstance().getAppearanceDelegate()
        val appearance = DSAppearance.Builder()
            .setActionBarColor(ColorDrawable(resources.getColor(R.color.colorPrimary)))
            .setStatusBarColor(ColorDrawable(resources.getColor(R.color.colorPrimaryDark)))
            .setActionBarLogo(ResourcesCompat.getDrawable(resources, R.drawable.ic_logo, null))
            .setActionBarTitleTextColor(ColorDrawable(resources.getColor(android.R.color.white)))
            .setBottomToolbarButtonColor(ColorDrawable(resources.getColor(R.color.colorPrimary)))
            .setBottomToolbarButtonTextColor(ColorDrawable(resources.getColor(android.R.color.white)))
            .setBottomToolbarDocuSignImageVisibility(true)
            .build()
        appearanceDelegate.appearance = appearance
```

**Comment by naveentds** [comment]
Hi @yusufonderd , can you let me know if you are using Online or Offline Signing. 
Also, can you let me know the OS version and Device details.
Here is the snapshot of the branding applied in the Offline Signing scenario based on the above API settings.

![Githubissue_branding](https://user-images.githubusercontent.com/66806694/161589702-98d8635a-edc6-42df-9998-cdeeac5c12a7.png)

If you don't see the UI similar to the above snapshot, post your screen snapshot with the branding settings applied.

**Comment by yusufonderd** [comment]
Hi,
My Device Pixel 3 API Tiramisu.
I'm using **launchCaptiveSigning** method for signing. 

```
val signingDelegate = DocuSign.getInstance().getSigningDelegate()
                val recipientClientUserId =
                    envelope.recipients?.firstOrNull()?.clientUserId.orEmpty()
                signingDelegate.launchCaptiveSigning(context,
                    envelope.envelopeId,
                    recipientClientUserId,
                    object : DSCaptiveSigningListener {
                       // override methods ...
                    })
                    

```
Because for my case online or offline signing didn't starting signing dialog. Only launchCaptiveSigning method works for me. Thanks.

**Comment by yusufonderd** [comment]
Still getting same issue.

**Comment by naveentds** [comment]
Hi
I tried offline signing scenario with Branding on Pixel 3 Tiramisu and the signing ceremony with branding is launched successfully. 
Please find the screenshot for reference.

![Branding_Tiramisu](https://user-images.githubusercontent.com/66806694/162835994-8ab402c7-9bb9-42b5-a481-a6f804b590d7.png)

**Comment by yusufonderd** [comment]
Hi, I will attach screenshot tomorrow. But i'm using only **launchCaptiveSigning** method for signing. I didn't using **signOffline** method. if you test with same scenario for **launchCaptiveSigning** method, you can see.

**Comment by naveentds** [comment]
Hi
For captive signing, branding won't be applied when you set via DocuSign Android SDK API. They are applied only for Offline and Online Signing. 
For captive signing, you need to set branding Id in the DocuSIgn web portal.
Take a look at https://youtu.be/IAPaUwv5TyU on how to create custom brand. 
You can just set brandId to the envelope and those branding settings will be applied automatically during signing.

**Comment by yusufonderd** [comment]
Thanks a lot. I can change branding from docusign portal. Youtube tutorials worked successfull.
