### ISSUE TITLE
Captive signing with URL issues - The "Upload Your Signature" button does not work

### ISSUE THREAD

**Issue by DassieKlip** [docusign/mobile-android-sdk#35]
Good day :)

When using `launchCaptiveSigning` with a URL (that's the only way we can use Docusign for our use case), signing works fine when drawing, or using a style, but when trying to upload a signature on the "Upload" tab by tapping the "Upload Your Signature" button, nothing happens - No asking for permission, or launching the Camera or Browse selector.

If the URL is copied into Chrome on the Android device, then tapping the "Upload Your Signature" button actually asks for the permission to access media and files, and then launches the Camera or Browse selector.

I tested this on:
- Emulators: Android API version 29 & 31
- Real-world devices: Android API version 22, 24, 27 & 30

There are no errors in the Logcat when tapping the button.

Am I not using captive signing with a URL correctly, or is there a problem with uploading a signature image from the Android device's storage?

Thank you for any assistance.

These permissions are declared in the Manifest:
```
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
<uses-permission android:name="android.permission.CAMERA" />
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
```

DocuSign is initialized in the Application class' `onCreate` fun as follows:
```
private fun initializeDocusign() {
    DocuSign.init(
        context = applicationContext,
        integratorKey = null,
        mode = forEnv(DSMode.DEBUG, DSMode.PRODUCTION),
    )

    DocuSign.getInstance().setEnvironment(forEnv(DSEnvironment.DEMO_ENVIRONMENT, DSEnvironment.PRODUCTION_ENVIRONMENT))

    val customSettingsDelegate = DocuSign.getInstance().getCustomSettingsDelegate()
    customSettingsDelegate.disableNativeComponentsInOnlineSigning(applicationContext, true)
    customSettingsDelegate.enableFileAccess(applicationContext, true)
}
```

Captive signing is launched as follows:
```
@Composable
private fun Docusign(
    eventDocusignStart: SharedFlow<CaptiveSigningParams>,
    onError: (Exception) -> Unit,
) {
    val context = LocalContext.current

    val signingDelegate = DocuSign.getInstance().getSigningDelegate()

    LaunchedEffect(eventDocusignStart) {
        eventDocusignStart
            .onEach { params ->
                signingDelegate.launchCaptiveSigning(context,
                    signingURL = params.url,
                    envelopeId = "", // Not needed when using URL
                    recipientId = null, // Not needed when using URL
                    object : DSCaptiveSigningListener {
                        override fun onCancel(envelopeId: String, recipientId: String) { }

                        override fun onError(envelopeId: String?, exception: DSSigningException) {
                            onError(exception)
                        }

                        override fun onRecipientSigningError(envelopeId: String, recipientId: String, exception: DSSigningException) { }
                        override fun onRecipientSigningSuccess(envelopeId: String, recipientId: String) { }
                        override fun onStart(envelopeId: String) { }
                        override fun onSuccess(envelopeId: String) { }
                    })
            }
            .launchIn(this)
    }
}
```

**Comment by naveentds** [comment]
@DassieKlip , Thanks for letting us know about the issue. Your code looks good to me. We will try to reproduce the issue on our end and get back to you.

**Comment by naveentds** [comment]
Hi @DassieKlip
We are able to reproduce the issue and we will fix this issue in our future SDK releases.

**Comment by naveentds** [comment]
@DassieKlip SDK v1.7.3 has been published and this issue has been resolved in this release. Try it out and let us know how it goes.
