### ISSUE TITLE
When screen sharing in debug mode, shows black screen

### ISSUE THREAD

**Issue by tim-nguyen** [docusign/mobile-android-sdk#37]
Hello,

When I am trying to screen share and show off docusign functionality with my test build it shows a black screen.
Is FLAG_SECURE being set when the docusign activity is present and if so can we clear it for the debug builds?

Thanks,
-T

**Comment by naveentds** [comment]
Hi @tim-nguyen 
You can enable screen share by invoking the following SDK API:
```DocuSign.getInstance().allowScreenCapture(true)```
