### ISSUE TITLE
Captive signing fails with error

### ISSUE THREAD

**Issue by bogdanheutschi** [docusign/mobile-android-sdk#38]
Hello,

I am trying to launch a captive signing with an envelopeId, but I get the error "Cannot Sign envelope for this recipient". 
This only happens when when we use the a standard based signature, like this:
       recipientSignatureProviders: [{
        signatureProviderName: 'UniversalSignaturePen_OpenTrust_Hash_TSP',
        signatureProviderOptions: { sms: @contract.everon_service.user.phone_number }
      }]
I have noticed that if I try to call RecipientUtils.isSigningBlocked(user), it returns that it is blocked with the text "Envelope recipient cannot be SBS Signer". 
Do you know if this can be enabled somehow?

**Comment by karankaushik95** [comment]
Hi Bogdan,

I tried to reproduce this and I was able to generate an envelope with a captive recipient with UniversalSignaturePen_OpenTrust_Hash_TSP. I suspect something else is going wrong here. I would recommend opening a support case with DocuSign Developer Support (https://developers.docusign.com/support/) so that I or one of my colleagues can assist you with debugging this.

**Comment by bogdanheutschi** [comment]
It seems the support page has some problems atm. Basically not the creation of the envelope is the problem, we are able to create the envelope using a ruby backend with the Ruby SDK. 
On the mobile side I've tried to launch the captive signing using the envelope ID but I got the error "Cannot Sign envelope for this recipient". 
Also I tried getting the envelope with the sdk and when I called RecipientUtils.isSigningBlocked(envelope.recipients?.get(0)!!) I got the error "Envelope recipient cannot be SBS Signer". 

Ruby code to create the envelope:

def make_envelope(signer_client_id, signer_email, signer_name, contract_id, language)
    envelope_definition = DocuSign_eSign::EnvelopeDefinition.new
    envelope_definition.email_subject = 'Please sign this document'

    document = DocuSign_eSign::Document.new
    document.document_base64 = Base64.encode64(@file.read)
    document.name = @contract.attachment.identifier
    document.file_extension = 'pdf'
    document.document_id = contract_id
    envelope_definition.documents = [document]

    signer_params = {
      email: signer_email,
      name: signer_name,
      clientUserId: signer_client_id,
      recipientId: 1,
      emailNotification: {
        emailSubject: '',
        emailBody: '',
        supportedLanguage: language
      },
      inheritEmailNotificationConfiguration: 'false',
      recipientType: 'signer'
    }

    if ENV['DOCUSIGN_AES_ENABLED'] == 'true'
      signer_params.merge!({ recipientSignatureProviders: [{
                             signatureProviderName: 'UniversalSignaturePen_OpenTrust_Hash_TSP',
                             signatureProviderOptions: { sms: @contract.everon_service.user.phone_number }
                           }] })
    end

    signer1 = DocuSign_eSign::Signer.new(signer_params)

    sign_here_instance = DocuSign_eSign::SignHere.new
    sign_here_instance.anchor_string = '/sn1/'
    sign_here_instance.anchor_units = 'pixels'
    sign_here_instance.anchor_x_offset = '4'
    sign_here_instance.anchor_y_offset = '4'

    tabs = DocuSign_eSign::Tabs.new({ signHereTabs: [sign_here_instance] })
    signer1.tabs = tabs

    recipients = DocuSign_eSign::Recipients.new
    recipients.signers = [signer1]

    envelope_definition.recipients = recipients
    envelope_definition.status = 'sent'
    
    envelope_api = Docusign::EnvelopeApi.call(args: args).instance
    results = envelope_api.create_envelope @account_id, envelope_definition
    results.envelope_id
  end
  
  Mobile code to launch the signing:
  
  DocuSign.getInstance().getSigningDelegate().launchCaptiveSigning(
            context = requireContext(),
            envelopeId = envelopeDto.envelopeId,
            recipientClientUserId = envelopeDto.client_user_id,
            listener = listener
        )

**Comment by karankaushik95** [comment]
I might have successfully reproduced your issue. Let me confirm if this is an intended behaviour/something else and I'll reply back

**Comment by karankaushik95** [comment]
I'm not too familiar with the Android SDK - I'd recommend opening a support case since it would be easier to trade information that way

**Comment by naveentds** [comment]
@bogdanheutschi DocuSign Android SDK currently does not support Standard based signatures for signing. We will add this feature in our future releases. Please reach out DocuSign Support and open a support case if you would like to get this prioritized.
