### ISSUE TITLE
Skip 'Host signing' page while using templates

### ISSUE THREAD

**Issue by aperdomom** [docusign/mobile-android-sdk#4]
I'm using DocuSign.getInstance().getTemplateDelegate().useTemplate() to launch signing ceremony and I would like to have the option to skip the  'Host signing' page.
![hostSigningPage](https://user-images.githubusercontent.com/9371485/91595096-370c4e00-e920-11ea-90bb-76ff79017250.png)

**Comment by naveentds** [comment]
Hi @aperdomom  We have released a new version 1.1.0 of DocuSign Android SDK which will resolve this issue. You can use useTemplateOnline() api to use template, set EnvelopeDefaults and launch Online signing. Please try and let us know how it goes.

**Comment by naveentds** [comment]
Auction.com confirmed that the issue got resolved with latest SDK release.
