### ISSUE TITLE
Dark/Light theme issue during in-person signing

### ISSUE THREAD

**Issue by sidrabasit** [docusign/mobile-android-sdk#40]
We are experiencing an issue with light/dark mode during in-person signing using the DocuSign Android SDK. An important feature of the application is that a user can select dark/light mode irrespective of the device theme. When the app theme and device theme differ, the app theme is changed after in-person signing and it is set to device mode. This issue only occurs when the user signs the template.
**Could you please explain how we can prevent the configuration of the theme from changing?**

Below are the steps to reproduce this issue:
1) The application should include drawable resources for light and dark themes.
2) Change the theme of the device to dark mode
3) Change the theme of the application to light mode
4) Perform an in-person signing
5) The UI mode has been changed to dark, and resources (drawables) are now being picked up from the drawable-night folder

**Comment by smd9788** [comment]
@sidrabasit - Are you using the DSTheme methods to control the theme? Can you please provide a code snippet where you use this method?

https://docusign.github.io/mobile-android-sdk/sdk-common/com.docusign.androidsdk.dsmodels/-d-s-theme/index.html

**Comment by sidrabasit** [comment]
We are not using this method. Below is a code snippet for initializing DocuSign: 
` fun init(
            context: Context,
            integrationKey: String,
            clientSecret: String,
            redirectUrl: String,
        ) {
            DocuSign
                .init(
                    context,
                    integrationKey,
                    clientSecret,
                    redirectUrl,
                    DS_MODE
                )
                .setEnvironment(DS_ENVIRONMENT)
            DocuSign.getInstance()
                .getCustomSettingsDelegate()
                .apply {
                    setDeclineToSignOnlineSigningOptionVisibility(context, false)
                    enableThirdPartyContentAccess(context, false)
                    enableFileAccess(context, false)
                    disableSigningCompleteScreen(context, true)
                    enableFileEncryption(context, true)
                }
        }
`

**Comment by naveentds** [comment]
Hi @sidrabasit , can you try to invoke the following SDK API to control theme and see if the issue is resolved:
```
val appearanceDelegate = DocuSign.getInstance().getAppearanceDelegate()
appearanceDelegate.setTheme(theme: DSTheme)
```

**Comment by sidrabasit** [comment]
Hi @naveentds, 
The issue persists even after applying the above code snippet.

**Comment by naveentds** [comment]
We will look into the issue and we will provide the fix in the next SDK release.

**Comment by naveentds** [comment]
Hi @sidrabasit 
- We are not able to reproduce the issue related to theme. It works fine. I tried to set the device theme to dark mode. I set light theme in the App and I see the light mode for signing screens being displayed and once signing is completed, in the App, it displays resources from drawable folder of the App itself. 
- Can you make sure that in the App, you are not re setting the theme mode back to System after signing is completed.
- If possible, can you send us the video of the issue.  
Thanks.

**Comment by sidrabasit** [comment]
Hi Naveen, 
Steps for reproducing the issue are as follows:
1) The user clicks on the sign field.
2) After signing the document, the user is redirected to a form screen from which API calls are made. The user is then taken to the success screen.
3) In the success screen, the drawables are taken from the drawable-night folder.

This issue will only occur when the device theme and application theme are different. As an example, if the application theme is light and the device theme is dark.

We have also verified that the theme was not updated after signing.

**Comment by naveentds** [comment]
Hi Sidra
The success screen is the screen from the App, its' not from SDK. Can you try to invoke Android SDK API to set the theme.
Eg:
If you want to set to lighter theme, then invoke the following API after the signing success callback is returned:
```
AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_NO) 
```
