### ISSUE TITLE
DocuSign Android SDK 1.7.7 does not display radio button values

### ISSUE THREAD

**Issue by sidrabasit** [docusign/mobile-android-sdk#41]
After upgrading to DocuSign Android SDK 1.7.7, we encountered an issue where the values in radio button fields weren't set. The values are assigned to the radio button tab when building the envelope. But the radio button doesn't have a value selected during in-person signing. This issue did not exist in the previous version.
Please let us know how we can fix this issue.

**Comment by SayedHhusseinDS** [comment]
Hello, reached out internally to check if there is any issue related to the same in this release, also asking if you could try to open a ticket with the developer support team and add your issue there to be able to follow up.
https://support.docusign.com/en/createCase

**Comment by naveentds** [comment]
Hi @sidrabasit 
This issue has been fixed in our latest SDK v1.7.8 release. Please try it out and let us know how it goes. 
Thanks.

**Comment by sidrabasit** [comment]
Sure. I will update the SDK and let you know.
