### ISSUE TITLE
SDK 1.7.8 - Document is not loading

### ISSUE THREAD

**Issue by meeramanesh** [docusign/mobile-android-sdk#42]
Good Day 

When doing **createEnvelopeAndLaunchOnlineSigning**, the DSOnlineSigningListener reaches  on

 override fun onStart(envelopeId: String) {
      Timber.d("onlineSign::onStart")
   }

But after that the document is not loading, instead blank white screen is getting displayed.
I found the below logs in the console.

before mSecurityLevel.createOperation
after mSecurityLevel.createOperation
before mSecurityLevel.createOperation
after mSecurityLevel.createOperation

 evaluateJS: DSSigning.init({    sendMessage: function(id, data) {        var filteredData = data instanceof Object ?JSON.stringify(data) : data;        DSSigningApplication.receiveMessage(id, filteredData);    },    suppress:{        addCCRecipientsDialog: true,        advancedPaymentDialog: true,        applyDigitalCertificateDialog: true,        comments: true,        sessionAboutToEndDialog: true,        signingErrorDialog: true    }});
Event cached successfully
Telemetry caching event successful

`[INFO:CONSOLE(2)] "TypeError: Cannot read properties of null (reading 'getItem')",  source: https://docucdn-a.akamaihd.net/demo/signing/signing-app/23.5.40/signing_iframeless_mobile.js?cs=33b911b5c (2)

[INFO:CONSOLE(2)] "Uncaught TypeError: Cannot read properties of null (reading 'getItem')",  source: https://docucdn-a.akamaihd.net/demo/signing/signing-app/23.5.40/signing_iframeless_mobile.js?cs=33b911b5c (2)

`
Testing in Real Device : Android version 12

**Comment by sylvainleb376** [comment]
Hello,

Would it be possible you provide the envelopeId generated for which you had this error?
Do you have this error systematically when you're running the function "createEnvelopeAndLaunchOnlineSigning"?
Thanks also to provide a full stack trace of this call.
Could you also confirm you're using at least these software versions:
	Android 5.0
	AndroidX
	Android Studio 3.4
	compileSdkVersion and targetSdkVersion 29
Maybe you should rather open a Docusign support ticket, it would be easier to exchange these kind of details.

Best regards,

Sylvain

**Comment by tomaszshowoff** [comment]
Hey folks,

Same thing happens with the Captive Signing. The app we've built has been in UAT for last 3 weeks and Docusign worked OK and stopped only a few days ago on all Android devices at the same time. The iOS seems to behave as expected. 

Issue:
I'm launching Captive Signing, the SDK opens, I see Docusign loading indicator and then just an empty grey screen.

Last log I'm getting from your SDK is:

`"TypeError: Cannot read properties of null (reading 'getItem')", source: https://docucdn-a.akamaihd.net/demo/signing/signing-app/23.5.40/signing_iframeless_mobile.js?cs=33b911b5c (2)
"Uncaught TypeError: Cannot read properties of null (reading 'getItem')", source: https://docucdn-a.akamaihd.net/demo/signing/signing-app/23.5.40/signing_iframeless_mobile.js?cs=33b911b5c (2)`

Tested with:

SDK ver: 1.7.7 - 1.8.1
Android ver: 8 - 12

Any chance of looking into this?

Thanks,
Tom

**Comment by naveentds** [comment]
@meeramanesh @tomaszshowoff This issue occurs on Demo environment and does not happen on Prod environments. This is a DocuSign backend issue and is resolved recently. Those changes will be pushed to Demo environment by end of tomorrow.

**Comment by tomaszshowoff** [comment]
Hi @naveentds

Thanks for such a prompt response. Will let our test users know.

Cheers,
Tom

**Comment by meeramanesh** [comment]
@naveentds 
Thanks  for the response.

**Comment by meeramanesh** [comment]
Hi @naveentds 
Is the changes are pushed to demo environment?
We are in a hurry for some critical releases for internal testing

**Comment by naveentds** [comment]
Hi @meeramanesh 
DocuSign server changes push is rescheduled to next week.
In the meanwhile, we added a fix in the SDK which resolves the empty white screen issue during signing.
Please get latest SDK v1.8.2 and let us know how it goes.

Thanks.

**Comment by meeramanesh** [comment]
Thanks @naveentds.
I have updated the SDK to 1.8.2 and the blank screen issue has been resolved.
I have noticed one thing as the randomly the documents are not getting loaded for the first time. When I try to open that in the second time its loading successfully. I haven't face this before versions.

Also we found that the demo environment is responding quite slow than usual in case of iOS and Android. 
Do you have any update for this? Is that dependent on your changes in backend?

Thanks in Advance.

**Comment by naveentds** [comment]
Hi @meeramanesh 
Our backend pushed changes to demo which resolves empty screen issue during signing. The slowness could have been the issue due to the backend changes being pushed.
You can continue using SDK 1.8.1. Please try it out and see if the issue has been resolved.  

Thanks
Naveen

**Comment by meeramanesh** [comment]
Thanks @naveentds 
I tried with SDK 1.8.1. Its working fine
