### ISSUE TITLE
Supplemental documents (Android-SDK)

### ISSUE THREAD

**Issue by iosense** [docusign/mobile-android-sdk#45]
Hi, support.

We are in a project to sign documents using android application (Kotlin) with (Docusign Android-SDK) and when we try to open envelope with supplemental documents one error occurs point to SDK exception.

<img width="798" alt="Screenshot 2024-02-16 at 11 00 40" src="https://github.com/docusign/mobile-android-sdk/assets/60938646/39e316eb-3457-4964-9fec-3bc49213e363">

This problem occurs only using SDK. Using docusign API work's fine with same envelope.

Docusign SDK Version: 1.9.2
Kotlin: 1.9.10
Android Version: 10/11

**Comment by naveentds** [comment]
Hi,
We currently don't support supplemental documents in Android SDK. Please reach out to our DocuSign Dev support if you have any questions related to new feature requests.

Thanks
Naveen
