### ISSUE TITLE
Error on Downloading PDF target api 34 - SecurityException

### ISSUE THREAD

**Issue by vdrahorad-paylocity** [docusign/mobile-android-sdk#46]
While attempting to download a PDF file via the DocuSign Android SDK screen for signing documents, the SDK screen exits without completing the download. This behaviour is accompanied by a logged error related to a SecurityException.

**Steps to Reproduce:**

- Open the DocuSign Android SDK.
- Navigate to the screen for signing documents.
- Initiate the PDF download process, accessed via the hamburger menu.
- Observe the SDK screen exiting unexpectedly.

The following error is logged:
`
One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts`

Target SDK: 34
**Additional Information:**
This issue seems to be related to changes in the target SDK (34) and the way broadcast receivers are registered within the application. It's likely that adjustments need to be made to ensure compatibility with the latest Android SDK requirements.

**Comment by naveentds** [comment]
Hi, 
We will look into this issue and will let you know once it is fixed in Android SDK.
Thanks.

**Comment by naveentds** [comment]
Hi,
This issue has been fixed in SDK v1.9.4 release. Please try it out and let us know how it goes.
Thanks.

**Comment by banasiak** [comment]
LGTM!
