### ISSUE TITLE
SDK adds READ_PHONE_STATE permission without any stated reasong

### ISSUE THREAD

**Issue by PDavidPaylocity** [docusign/mobile-android-sdk#47]
Hello,

the SDK adds the `READ_PHONE_STATE` permission, which could be potentially problematic when uploading the app to Google Play, but there is no mention of it anywhere in the documentation. Please clarify

**Comment by mike-mej** [comment]
we solely utilize the READ_PHONE_STATE permission for signal strength retrieval, customers should encounter no issues when uploading the app to Google Play.
