### ISSUE TITLE
Docusign is asking location permission on initialisation step is there a way to disable it?

### ISSUE THREAD

**Issue by oguzozcan** [docusign/mobile-android-sdk#49]
Hello, 

Upon initialisation our users are being asked for providing location permission, while testing i didn't give location permission and everything was still working as expected. I am wondering is there a way to cancel this location permission request?

We can't see any effect on user experience, is there a specific use case for requesting location permission?

Thank you

**Comment by naveentds** [comment]
Hi,
Users will see location request on android devices with versions lower than 33. 
On android versions 33 and above, you may not see location permission. On later versions, android OS controls display of location permission to the user. This works as designed.

**Comment by oguzozcan** [comment]
Thanks for the reply. 
My concern is not the visibility of the location permission dialog but the reason to it. I don't know every other usecase you are handling ofcourse but we don't use location services while user is filling the form or we don't see any value to it for now, as there is no way as far as i know to fill the user address/zip code or any address related information automatically, please correct me if i am wrong.

As far as i understand from your answer its needed but will there be a configuration to disable requesting permission? Can we use your library without providing location?

**Comment by naveentds** [comment]
By default, Docusign will include a signer's IP address in the Certificate of Completion as part of the full audit trail of a document. The location of a signer can only be roughly determined with this information.
If a signer opts in to share their location during signing, location information allows Docusign to display the 'Signed in Location' on a map from within the envelope's details under the Manage tab.

If we want to provide a configuration from SDK to disable requesting permission, that will be a separate enhancement request. We will check with our Product and add to the Roadmap.

**Comment by oguzozcan** [comment]
Thank you very much understood. I don't know your process but ticket can be closed i suppose
