### ISSUE TITLE
How to handle the size of the radio button on the docusign document

### ISSUE THREAD

**Issue by malaynagarro** [docusign/mobile-android-sdk#51]
hey ,

We were using DocuSign online signing, but due to some issues, we had to switch to offline signing. However, offline signing has a UI issue where the radio buttons or checkboxes overlap with the text or description associated with them. Is there a way to change the size of the radio buttons or checkboxes through the DocuSign portal?
Below is the code for reference.
Build : - Android SDK
DocuSign version : - 1.9.4
```
    private suspend fun createDocuSignEnvelope(index: Int, docusignTemplateCode: String): EnvelopeSendResult? {
        return try {
            finalReview.templates.firstOrNull { it.docusignTemplateCode == docusignTemplateCode }?.let { template ->
                val templateId = template.docusignTemplateID
                val templateName = template.docusignTemplateDisplayName
                val templateCode = template.docusignTemplateCode
                val signerName = finalReview.formData.investorDetails?.personalDetails?.let {
                    "${it.firstName} ${it.middleName ?: ""} ${it.lastName}"
                } ?: "Investor" // It shouldn't be null
                val signerEmail = userUseCase.getAuthenticatedUserEmail()
                    ?: "support@investcorp.com" // It shouldn't be null
                val signatoryDetails = arrayListOf(
                    RecipientInfo(
                        (index + 2).toString(),
                        (index + 2),
                        signerName,
                        signerEmail,
                    )
                )
                docuSignWrapper.composeAndSendEnvelopeFromTemplate(
                    envelopeName = templateName,
                    templateId = templateId,
                    tabsMap = tabMapByName(templateCode),
                    signatoryDetails = signatoryDetails
                )
            }
        } catch (e: Exception) {
            Timber.e(e)
            null
        }
    }
```

<img width="293" alt="docusign" src="https://github.com/docusign/mobile-android-sdk/assets/148522151/8de4e325-1375-4d4b-83c0-61c7960a3920">

@naveentds required immediate help on this above context.
thank you.

**Comment by naveentds** [comment]
Hi
We just want to let you know that the issue related to online signing has been resolved as mentioned in the other github issue ticket.
The image uploaded in the ticket showing the radio buttons is not viewable as it returns 404 when I tried to open the attached image.
It looks like you are using template. If you have to use offline signing feature, you can try adjusting the radio buttons positions and size in the template in Docusign portal and check if the radio buttons are positioned correctly.

**Comment by malaynagarro** [comment]
hey,

Thank you for the response 
We will look into it.
and thank you for resolving the online signing issue on priority.

**Comment by naveentds** [comment]
We are closing the issue for now and let us know if there are any other questions.
