### ISSUE TITLE
In Person ID Check Question is not working

### ISSUE THREAD

**Issue by aperdomom** [docusign/mobile-android-sdk#6]
I set "In Person ID Check Question" in DocuSign web portal and the In-person signer does not get the question before signing in android app.

**Comment by naveentds** [comment]
Hi @aperdomom  We have released a new version 1.1.0 of DocuSign Android SDK which will resolve this issue. You can use useTemplateOnline() api to use template and launch Online signing. In the app, during signing, it will display the question which you set "In person ID Check" in DocuSign web portal. Please try and let us know how it goes.

**Comment by naveentds** [comment]
Auction.com confirmed that the issue got resolved with latest SDK release.
