### ISSUE TITLE
Envelop id not sync in android

### ISSUE THREAD

**Issue by vishalkushwaha-sdei** [docusign/mobile-android-sdk#7]
Hello Team,

After receiving the envelopeId in `onComplete(String envelopeId)` of `useTemplate()` API , I invoke `DocuSign.getInstance().getEnvelopeDelegate().syncAllEnvelopes()` and in callback `onEnvelopeSyncSuccess(localEnvelopeId: kotlin.String, serverEnvelopeId: kotlin.String?)` it return local envelop id and new envelop Id, but when I check in sandbox/ docusign webpotal there is no any envelop entry and also home - completed secion is also empty there is no any sign document.

**Comment by naveentds** [comment]
@vishalkushwaha-sdei  If you point the environment to DEMO environment using SDK api, you can check signed/completed envelope if you navigate to https://demo.docusign.net in web.
If you point the environment to PROD environment using SDK api, you can check signed/completed envelope if you navigate to https://docusign.net in web.

**Comment by vishalkushwaha-sdei** [comment]
Hii @naveentds 

Thanks for the response now we are able to see the synced envelop Id...

But now we are facing some other queries/issues.
Actually when our backend developer tries to take the signature for the envelope id created by the android by hitting the API -
`/restapi/v2.1/accounts/{accountId}/envelopes/{envelopeId}/recipients/{recipientId}/signature_image` 

So we are getting **Resource not Found Error**... but when we are hit the same API with IOS - envelop id (Envelope synced by the IOS ). on we get the image of signature...

After making some research we found some points:
1.  After syncing the envelope id with Android the entry of that envelop id is shown in the **folder of sent** Where the IOS envelop Id is shown in the **folder of inbox**.

2. And when we hit this API - `/restapi/v2.1/accounts/{accountId}/envelopes/{envelopeId}/recipients`  - On the response we found the two difference .
  
  i. **role name** has not come in the **android** envelope id  where the role name is **IOS** envelop ID
  ii. In android **delivery method** is show _offline_ but IOS it shows _email_

In android before signature **(Refer Image)**
![91595096-370c4e00-e920-11ea-90bb-76ff79017250](https://user-images.githubusercontent.com/70007145/94176573-edc70400-feb5-11ea-9f0c-cbf9d72477a6.png)
why we need to go with the **Host signature**. where in IOS there is no such step need to follow.

Thanks, 

I am requesting you to kindly look at these issues if you are facing difficulty to understand some point so let me know,

We are looking forward to your positive reply...

**Comment by naveentds** [comment]
@vishalkushwaha-sdei  Nice to hear that you are able to see the synced envelopes now.
You must be using iOS Online signing apis. Android SDK does not support Online signing yet. It is a work in progress and will be available in 1.1 release. We are anticipating 1.1 release around October mid. 
Reg the signature image using REST api, when you used Online signing in Android SDK, you should be able to fetch signature image using REST api.
Reg. the 'Use template' screen, it is displayed when using Offline Signing. If you use Online signing which will be available in 1.1, then 'Use template' screen won't appear and will launch signing ceremony directly.

**Comment by naveentds** [comment]
@vishalkushwaha-sdei  DocuSign Android SDK v 1.1.0 has been released which includes OnlineSigning feature. Please try and let us know how it goes.
